
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "vite-react"

#   config.vm.network "forwarded_port", guest: 5173, host: 5173
  config.vm.network "forwarded_port", guest: 3000, host: 3000


  config.vm.provision 'chef_zero' do |chef|
    chef.arguments = "--log_level debug --chef-license accept-silent"
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe 'heroes_app'
    chef.nodes_path = 'nodes'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
  end
end